# Generated by Django 3.0.2 on 2020-03-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captrue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('one_xinyong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('place', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('shenhe', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('xiajia', models.BooleanField(default=False)),
                ('usertype', models.SmallIntegerField(choices=[(1, '招人'), (2, '求职')], verbose_name='分类')),
                ('status', models.BooleanField(default=False)),
                ('s_tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('usertype', models.SmallIntegerField(choices=[(1, '商户'), (0, '个人')], verbose_name='性别')),
                ('imagepath', models.ImageField(upload_to='')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], verbose_name='性别')),
                ('xinyong', models.IntegerField()),
                ('money', models.IntegerField(default=0)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('lastlogin_date', models.DateTimeField(auto_now=True)),
                ('is_heshi', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('idcardpath', models.ImageField(upload_to='')),
                ('idcardpath1', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Usertojob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('u_tel', models.CharField(max_length=11, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.Subject')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.User')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.User'),
        ),
        migrations.AddField(
            model_name='subject',
            name='wages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.Wages'),
        ),
        migrations.AddField(
            model_name='subject',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.Captrue'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('is_no', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.Subject')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='系统通知:', max_length=128)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partjob.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partjob.Comment')),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.Subject')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partjob.User')),
            ],
        ),
    ]
