# Generated by Django 3.0.2 on 2020-03-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partjob', '0002_auto_20200308_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yingyezhizhao',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
