# Generated by Django 3.0.2 on 2020-03-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partjob', '0003_user_yingyezhizhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertojob',
            name='for_pass',
            field=models.BooleanField(default=False),
        ),
    ]
