# Generated by Django 3.0.2 on 2020-03-10 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partjob', '0004_usertojob_for_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertojob',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
